# Generated by Django 5.2.5 on 2025-08-15 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_purchasedetail_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
