# Generated by Django 5.2.5 on 2025-08-15 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_saledetail_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemaster',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
    ]
